import { reactive } from 'vue'
import type { DayMessages } from '@/types/message'

export const officeMessages: DayMessages[] = reactive([
  {
    daySep: '今天 · 2026年6月12日',
    messages: [
      {
        id: 'o1',
        sender: { type: 'human', name: '林经理', avatar: '林', color: '#7a5a3a' },
        time: '11:30',
        html: '@质检分身 把今天 4000 斤加急订单的<b>质检与溯源报告</b>整理出来，要发给渠道客户。'
      },
      {
        id: 'o2',
        sender: { type: 'bot', name: '质检分身', avatar: '质' },
        time: '11:30',
        html: '好的。已从 <code>质检实验室 / 溯源链 / 冷链温控平台</code> 自动汇总本批次数据，报告如下，请审阅：',
        doc: {
          title: '蓝湾渔业 · 批次质检与溯源报告',
          subtitle: '订单 #SO-0612-01 · 生鲜海鱼 4,000 斤 · 2026 年 6 月 12 日 · 接收方：渠道客户',
          sections: [
            {
              title: '一、批次构成与质检结果',
              body: '本订单货源由三个批次构成，按「冷库优先 → 养殖补量 → 捕捞收尾」分配，<b>抽检合格率 100%</b>。',
              table: {
                headers: ['来源', '批次号', '数量', '质检结果'],
                rows: [
                  ['冷库库存', '#LK-0610-3', '2,000 斤', { text: '合格', color: '#6b8e4e' }],
                  ['养殖出塘（1 号塘）', '#YZ-0612-7', '1,500 斤', { text: '合格', color: '#6b8e4e' }],
                  ['捕捞渔获（闽蓝 012）', '#BL-0612-2', '500 斤', { text: '合格', color: '#6b8e4e' }]
                ]
              }
            },
            {
              title: '二、检测项目',
              body: '农药残留 / 兽药残留 / 重金属（铅、镉、汞）均<b>未检出</b>；鲜度 K 值 12%，达<b>一级鲜度</b>标准；菌落总数符合 GB 2733 生食水产品限值。'
            },
            {
              title: '三、全链路溯源',
              body: '海域 / 塘口 → 捕捞 · 出塘 → 冷藏转运 → 入厂质检 → 分拣包装 → 冷链配送，<b>6 个节点</b>的时间、责任人、温控记录已全部上链存证，扫码即可向客户展示。'
            },
            {
              title: '四、结论与建议',
              body: '1. 本批次<b>准予出厂</b>，质检报告编号 #QC-0612-15；<br/>2. 冷链运输全程厢温 ≤ 4℃，建议 36 小时内完成交付；<br/>3. 留样已封存 72 小时备查。'
            }
          ],
          footer: '// generated by GuDuu · 2026-06-12 11:30 · v0.3',
          actions: [
            { label: '下载 .pdf', primary: true },
            { label: '推送给客户' },
            { label: '在画布中编辑' }
          ]
        }
      }
    ]
  }
])
